### ISSUE TITLE
Remove test fields and indices

### ISSUE THREAD

**Issue by kaerumy** [Sinar/politikus.contenttypes#4]
Remove test fields and indices from master

**Comment by JustineSurGithub** [comment]
Fixed with [https://github.com/Sinar/politikus.contenttypes/commit/cad9fd2f1170d24b865320ab14cb6eaeb8da8a7a](url) & [https://github.com/Sinar/politikus.contenttypes/commit/4842f07d0a0a3d6f506ef4f1ae3cfd1628f631f5](url).
